import { chromium } from 'playwright';
const OUT = process.argv[2] || '/tmp';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1477, height: 900 }, deviceScaleFactor: 1.5 });
const p = await ctx.newPage();
const errs = [];
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text().slice(0, 140)); });
await p.goto('http://localhost:8080/lab/heroflow', { waitUntil: 'domcontentloaded' });
await p.waitForSelector('.hfl-fills', { timeout: 15000 });
await p.click('text=Zmerať výplň');
await p.waitForTimeout(14000);
await p.screenshot({ path: `${OUT}/lab-vyplne.png` });
const t = await p.$$eval('.hfl-fillrow', (rows) => rows.map((r) => r.textContent));
console.log('tabuľka:', JSON.stringify(t));
// HRANICA zapnutá + otvorená povaha
await p.click('text=HRANICA');
await p.click('text=7 · Povaha (dve vlastnosti)');
await p.waitForTimeout(3000);
await p.screenshot({ path: `${OUT}/lab-hranica.png` });
console.log(errs.length ? `CHYBY: ${errs.slice(0, 3).join(' | ')}` : 'konzola čistá');
await b.close();
