export const photoPositions: Record<string, string> = {
  "ARNOLD.jpg":          "50% 23.4%",
  "BERRY.jpg":           "50% 76.6%",
  "CONAN.jpg":           "50% 28%",
  "FROSTY.jpg":          "50% 23.4%",
  "HAKY.jpg":            "50% 50%",
  "JAkub.jpg":           "50% 50%",
  "LESIE.jpg":           "50% 14.8%",
  "MACO.jpg":            "50% 25%",
  "MARLEY.jpg":          "50% 47.2%",
  "MIA.jpg":             "50% 50%",
  "NELA.jpg":            "50% 23.4%",
  "alastor.jpeg":        "50% 17.6%",
  "alby.jpg":            "50% 14.1%",
  "amadeo.jpg":          "50% 70%",
  "amadeo2.jpg":         "50% 50%",
  "baron.jpg":           "50% 46.9%",
  "bassotto.jpg":        "50% 50%",
  "bax.jpg":             "50% 41.7%",
  "belga.jpg":           "50% 23.4%",
  "bleky.jpg":           "50% 23.5%",
  "bono.jpg":            "50% 20.6%",
  "bruno.jpg":           "50% 20.8%",
  "buddy.jpg":           "50% 17.6%",
  "caro.jpg":            "50% 68.8%",
  "charlie.jpeg":        "50% 17.6%",
  "conor.jpg":           "50% 50%",
  "danda.jpg":           "50% 23.4%",
  "dexter.jpg":          "50% 23.4%",
  "dia.jpg":             "50% 50%",
  "diaz1.jpg":           "50% 50%",
  "diorko.jpg":          "50% 30.2%",
  "dorotka.jpg":         "50% 22%",
  "freya.jpg":           "50% 14.4%",
  "hiro.jpeg":           "50% 30%",
  "hugo.jpg":            "50% 17.6%",
  "ichie.jpg":           "50% 20.6%",
  "jackie.jpg":          "50% 23.4%",
  "junior.jpg":          "50% 23.4%",
  "kevin.jpg":           "50% 20.8%",
  "lila.jpeg":           "50% 23.4%",
  "loki.jpg":            "50% 30%",
  "lory.jpg":            "50% 46.9%",
  "luna.jpg":            "50% 41.7%",
  "lusy.jpg":            "50% 41.7%",
  "majla.jpeg":          "50% 49.8%",
  "mars.jpg":            "50% 23.4%",
  "maxik.jpg":           "50% 23.4%",
  "maxo.jpg":            "50% 23.4%",
  "maya.jpg":            "50% 50%",
  "mily.jpg":            "50% 23.4%",
  "miuska.jpg":          "50% 17.6%",
  "miuskaa.jpg":         "50% 25%",
  "nela ina.jpg":        "50% 46.9%",
  "neo.jpeg":            "50% 17.6%",
  "oreo.jpg":            "50% 23.4%",
  "pipa.jpg":            "50% 14.1%",
  "remus.jpg":           "50% 20.5%",
  "sheldon.jpg":         "50% 25.5%",
  "simba.jpg":           "50% 25.2%",
  "tara.jpg":            "50% 20.9%",
  "tayen.jpg":           "50% 23.4%",
  "toby.jpg":            "50% 50%",
  "yogi.jpg":            "50% 50%",
  "zia.jpg":             "50% 23.4%",
  "zoro.jpg":            "50% 76.6%",
};

export const photos = [
  { f: 'ARNOLD.jpg',            n: 'Arnold' },
  { f: 'BERRY.jpg',             n: 'Berry' },
  { f: 'CONAN.jpg',             n: 'Conan' },
  { f: 'FROSTY.jpg',            n: 'Frosty' },
  { f: 'HAKY.jpg',              n: 'Haky' },
  { f: 'JAkub.jpg',             n: 'Jakub' },
  { f: 'LESIE.jpg',             n: 'Lesie' },
  { f: 'MACO.jpg',              n: 'Maco' },
  { f: 'MARLEY.jpg',            n: 'Marley' },
  { f: 'MIA.jpg',               n: 'Mia' },
  { f: 'NELA.jpg',              n: 'Nela' },
  { f: 'alastor.jpeg',          n: 'Alastor' },
  { f: 'alby.jpg',              n: 'Alby' },
  { f: 'amadeo.jpg',            n: 'Amadeo' },
  { f: 'amadeo2.jpg',           n: 'Amadeo' },
  { f: 'baron.jpg',             n: 'Baron' },
  { f: 'bassotto.jpg',          n: 'Bassotto' },
  { f: 'bax.jpg',               n: 'Bax' },
  { f: 'belga.jpg',             n: 'Belga' },
  { f: 'bleky.jpg',             n: 'Bleky' },
  { f: 'bono.jpg',              n: 'Bono' },
  { f: 'bruno.jpg',             n: 'Bruno' },
  { f: 'buddy.jpg',             n: 'Buddy' },
  { f: 'caro.jpg',              n: 'Caro' },
  { f: 'charlie.jpeg',          n: 'Charlie' },
  { f: 'conor.jpg',             n: 'Conor' },
  { f: 'danda.jpg',             n: 'Danda' },
  { f: 'dexter.jpg',            n: 'Dexter' },
  { f: 'dia.jpg',               n: 'Dia' },
  { f: 'diaz1.jpg',             n: 'Diaz' },
  { f: 'diorko.jpg',            n: 'Diorko' },
  { f: 'dorotka.jpg',           n: 'Dorotka' },
  { f: 'freya.jpg',             n: 'Freya' },
  { f: 'hiro.jpeg',             n: 'Hiro' },
  { f: 'hugo.jpg',              n: 'Hugo' },
  { f: 'ichie.jpg',             n: 'Ichie' },
  { f: 'jackie.jpg',            n: 'Jackie' },
  { f: 'junior.jpg',            n: 'Junior' },
  { f: 'kevin.jpg',             n: 'Kevin' },
  { f: 'lila.jpeg',             n: 'Lila' },
  { f: 'loki.jpg',              n: 'Loki' },
  { f: 'lory.jpg',              n: 'Lory' },
  { f: 'luna.jpg',              n: 'Luna' },
  { f: 'lusy.jpg',              n: 'Lusy' },
  { f: 'majla.jpeg',            n: 'Majla' },
  { f: 'mars.jpg',              n: 'Mars' },
  { f: 'maxik.jpg',             n: 'Maxik' },
  { f: 'maxo.jpg',              n: 'Maxo' },
  { f: 'maya.jpg',              n: 'Maya' },
  { f: 'mily.jpg',              n: 'Mily' },
  { f: 'miuska.jpg',            n: 'Miuska' },
  { f: 'miuskaa.jpg',           n: 'Miuska' },
  { f: 'nela ina.jpg',          n: 'Nela' },
  { f: 'neo.jpeg',              n: 'Neo' },
  { f: 'oreo.jpg',              n: 'Oreo' },
  { f: 'pipa.jpg',              n: 'Pipa' },
  { f: 'remus.jpg',             n: 'Remus' },
  { f: 'sheldon.jpg',           n: 'Sheldon' },
  { f: 'simba.jpg',             n: 'Simba' },
  { f: 'tara.jpg',              n: 'Tara' },
  { f: 'tayen.jpg',             n: 'Tayen' },
  { f: 'toby.jpg',              n: 'Toby' },
  { f: 'yogi.jpg',              n: 'Yogi' },
  { f: 'zia.jpg',               n: 'Zia' },
  { f: 'zoro.jpg',              n: 'Zoro' },
];
