#!/usr/bin/env node
/**
 * Sync /codex Sacred Index from the Constitution HTML.
 *
 * Source of truth:  vystupy/constitution/index.html
 *   - section.part[id^="cast-"]  with data-codex-name + data-codex-desc
 *   - sub-headings (h3 / h4) with data-codex-en
 *
 * Output:           vystupy/web/src/data/sacredIndex.generated.ts
 * Run:              npm run sync-codex   (cwd = vystupy/web/)
 *
 * Fail-loud: missing attribute, wrong section count, or 0 subs → exit 1.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, relative } from 'node:path';
import { JSDOM } from 'jsdom';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../../..');
const SOURCE = resolve(REPO_ROOT, 'vystupy/constitution/index.html');
const OUTPUT = resolve(HERE, '../src/data/sacredIndex.generated.ts');

const html = readFileSync(SOURCE, 'utf8');
const doc = new JSDOM(html).window.document;

const romanFromPartNum = (text) => {
  const m = text.match(/Časť\s+([IVX]+\.)/);
  return m ? m[1] : null;
};

const errors = [];
const sections = [...doc.querySelectorAll('section.part[id^="cast-"]')];

const result = sections.map((sec) => {
  const id = sec.id;
  const name = sec.getAttribute('data-codex-name');
  const desc = sec.getAttribute('data-codex-desc');
  const partNum = sec.querySelector('.part-num')?.textContent?.trim() ?? '';
  const num = romanFromPartNum(partNum);
  const subs = [...sec.querySelectorAll('[data-codex-en]')]
    .map((el) => el.getAttribute('data-codex-en'));

  if (!name) errors.push(`${id}: missing data-codex-name on <section>`);
  if (!desc) errors.push(`${id}: missing data-codex-desc on <section>`);
  if (!num) errors.push(`${id}: cannot extract roman numeral from "${partNum}"`);
  if (subs.length === 0) errors.push(`${id}: 0 sub-headings (no [data-codex-en] inside section)`);

  return { num, name, desc, subs };
});

if (result.length !== 12) {
  errors.push(`expected exactly 12 sections (cast-i..cast-xii), got ${result.length}`);
}

if (errors.length) {
  console.error('[sync-codex] FAILED:');
  errors.forEach((e) => console.error('  · ' + e));
  process.exit(1);
}

const header =
  '// AUTO-GENERATED by scripts/sync-codex.mjs — DO NOT EDIT BY HAND.\n' +
  '// Source of truth: vystupy/constitution/index.html\n' +
  '// Regenerate: npm run sync-codex (cwd = vystupy/web/)\n\n' +
  'export type ChapterRow = {\n' +
  '  num: string;\n' +
  '  name: string;\n' +
  '  desc: string;\n' +
  '  subs: string[];\n' +
  '};\n\n' +
  'export const SACRED_INDEX: ChapterRow[] = ' +
  JSON.stringify(result, null, 2) +
  ';\n';

writeFileSync(OUTPUT, header, 'utf8');

const totalSubs = result.reduce((n, r) => n + r.subs.length, 0);
console.log(`[sync-codex] OK · ${result.length} chapters · ${totalSubs} sub-headings`);
console.log(`[sync-codex] wrote ${relative(REPO_ROOT, OUTPUT)}`);
