// AUTO-GENERATED by scripts/sync-codex.mjs — DO NOT EDIT BY HAND.
// Source of truth: vystupy/constitution/index.html
// Regenerate: npm run sync-codex (cwd = vystupy/web/)

export type ChapterRow = {
  num: string;
  name: string;
  desc: string;
  subs: string[];
};

export const SACRED_INDEX: ChapterRow[] = [
  {
    "num": "I.",
    "name": "CANON",
    "desc": "who we are",
    "subs": [
      "The Founding Myth",
      "GOD is DOG",
      "The Age of the Dog",
      "The Syncretic Clause"
    ]
  },
  {
    "num": "II.",
    "name": "CREDO",
    "desc": "what we believe",
    "subs": [
      "Seven Truths About Dogs",
      "The DOG-GOD Philosophy",
      "The Present Moment"
    ]
  },
  {
    "num": "III.",
    "name": "COMMANDMENTS",
    "desc": "how we act",
    "subs": [
      "The Ten Duties of a Dogyptian",
      "The Seven Sins",
      "The Seven Virtues",
      "Duties to the Dog Race",
      "Mantra of the Community",
      "The Proud Dogyptian"
    ]
  },
  {
    "num": "IV.",
    "name": "SACRAMENTS",
    "desc": "how we pray",
    "subs": [
      "The Sacraments",
      "The Prayers",
      "Feasts & Calendar",
      "Life Rituals"
    ]
  },
  {
    "num": "V.",
    "name": "HIERARCHY",
    "desc": "who is who",
    "subs": [
      "HEKTHOR I.",
      "The Pharaoh",
      "The Dogyptian Council",
      "The Conscious Dog Person"
    ]
  },
  {
    "num": "VI.",
    "name": "SACRED PLACES",
    "desc": "where we gather",
    "subs": [
      "dogypt.com — The Virtual Temple",
      "DOGYPT Centres",
      "DOGYPTLAND",
      "Local Circles"
    ]
  },
  {
    "num": "VII.",
    "name": "TEXTS",
    "desc": "what we read",
    "subs": [
      "The DOGYPT Constitution",
      "The Heroglyph Manual",
      "Cesta s Hrdinom (The Hero’s Journey)"
    ]
  },
  {
    "num": "VIII.",
    "name": "LANGUAGE",
    "desc": "how we speak",
    "subs": [
      "Dogyptish",
      "The Heroglyph",
      "Liturgical Colours",
      "Identification",
      "The DOGYPT Logo"
    ]
  },
  {
    "num": "IX.",
    "name": "ECONOMY",
    "desc": "how we sustain",
    "subs": [
      "Principles Binding From Day One",
      "Deferred for Later Revision"
    ]
  },
  {
    "num": "X.",
    "name": "INSTITUTIONS",
    "desc": "how we govern",
    "subs": [
      "Layer 1 — The Movement",
      "Layer 2 — Slovak Civic Association",
      "Layer 3 — USA 501(c)(3) Nonprofit",
      "Layer 4 — Church of Slovakia",
      "Layer 5 — International Umbrella"
    ]
  },
  {
    "num": "XI.",
    "name": "EXPANSION",
    "desc": "how we grow",
    "subs": [
      "Phase Slovakia (2026)",
      "Phase USA (2027)",
      "Phase Europe (2027–2028)",
      "Phase World (2028+)",
      "The “Same Story” Principle"
    ]
  },
  {
    "num": "XII.",
    "name": "ANTI-DOCTRINES",
    "desc": "what we are not",
    "subs": [
      "Not a Cult",
      "Not a Personality Cult",
      "Not a Competitor to Other Faiths",
      "Not Anti-Veterinary",
      "Not Empty MLM",
      "Not Vegan / Anti-Meat Ideology",
      "Not a Political Project"
    ]
  }
];
